### ISSUE TITLE
blank screen after payment

### ISSUE THREAD

**Issue by etman55** [tamara-solution/android-sdk#1]
I added the sdk to my app and after processing with the payment in sandbox environment i got a white blank screen with no redirects to my activity

**Comment by tamara-solution** [comment]
Hi @etman55 can you please share with us some debug logs from your side, should be request and response or exception message to tech-tool@tamara.co and we will investigate and fix if it's a bug.

Many thanks for your cooperation.

**Comment by etman55** [comment]
you can find my logs in here:

```
I/chromium: [INFO:CONSOLE(1)] "SyntaxError: Unexpected token u in JSON at position 0", source: https://checkout-sandbox.tamara.co/static/js/app.f5f52959.js (1)
D/OnePlusJankManager:  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = ibtikar.tania.user/co.tamara.sdk.TamaraPaymentActivity--- jank level = 1
D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@1221bf3[TamaraPaymentActivity]
D/Tamara: url: https://website-stage.tania.sa/tamara/cancel
I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'getItem' of null", source: https://website-stage.tania.sa/static/js/main.9ad71436.chunk.js (1)
```

**Comment by tamara-solution** [comment]
Can you please let us know how did you implement the flow? The SDK only handles the checkout flow by open a webview on the checkout url you got back from your Backend API.

**Comment by etman55** [comment]
I just added this line from readme file
`TamaraPayment.startPayment(activity, checkoutURL)`
