### ISSUE TITLE
inquire for tamara payment in Android SDK

### ISSUE THREAD

**Issue by FatimaSalman** [tamara-solution/android-sdk#2]
Hello everyone, 

I want to know how to get the API_URL , AUTH_TOKEN,NOTIFICATION_WEB_HOOOK_URL to use it in my project 

best regards,

**Comment by tamara-solution** [comment]
Dear @FatimaSalman,

Please use this form to contact our partner team: https://share.hsforms.com/1Mm-Og3VaSLOQ3Hg1uFmc0g8mvj3

**Comment by tamara-solution** [comment]
By the way, which merchant/shop are you working for @FatimaSalman?

**Comment by FatimaSalman** [comment]
thanks for replay me, I solve the problem.. but I need to handle the url that return from SDKs when the transaction failure, success and cancel in the android app -- Freesia shop

**Comment by tamara-solution** [comment]
Hi @FatimaSalman I think our Support Team is working with you on this.

**Comment by FatimaSalman** [comment]
yes, they is working, and waiting you
